version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db_fast_api
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testetecnico
      POSTGRES_DB: db_fast_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
