"""Create product table

Revision ID: 4af1b693bc14
Revises: d8cbd2db1e4f
Create Date: 2025-05-25 20:48:43.120931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af1b693bc14'
down_revision: Union[str, None] = 'd8cbd2db1e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sale_value', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('initial_stock', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', name='uq_barcode'),
    sa.UniqueConstraint('section')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
